class Projects {
  final String proj_id;
  final String title;
  final String images;
  final String category;
  final String description1;
  final String description2;

  Projects({
    required this.proj_id,
    required this.title,
    required this.images,
    required this.category,
    required this.description1,
    required this.description2,
  });
}

final List<Projects> projectList = [
  Projects(proj_id: '1', title: '1 Nito Tower', images: 'https://enyecontrols.com/ec_cpanel/images/projects/1622619484.jpg', category: '1', description1: 'Differential Pressure Transmitters', description2: '1 Nito Tower is a Grade A, 18-storey office and retail tower that spans a total of 40,000 sq. meters of leasable space. It is the first venture of King Properties, Inc in producing larger office spaces in Cebu that are purely for lease.'),
  Projects(proj_id: '2', title: '8912 Aseana', images: 'https://enyecontrols.com/ec_cpanel/images/projects/1622620662.jpg', category: '1', description1: 'Building Mangement System', description2: '8912 Aseana Avenue is a 15-storey building located in Aseana City, Paranaque City. Due to its prime location, the building is easily accessible to different modes of transportation.'),
  Projects(proj_id: '3', title: 'Alveo Financial Tower', images: 'https://enyecontrols.com/ec_cpanel/images/projects/1622620397.png', category: '1', description1: 'Fuel Level Control And Monitoring System Transformer Room Control And Monitoring System, Butterfly, Motorized, Fan Coil Valves And Actuator, Btu Meter, Damper Actuator', description2: 'Alveo Financial Tower an office building with plans for retail areas on its first three floors as well as a (business activity area) on the 5th and 17th floors. The tower will host 363 office units.'),
  Projects(proj_id: '4', title: 'Alveo High Park', images: 'https://enyecontrols.com/ec_cpanel/images/projects/1622620529.jpg', category: '1', description1: 'Tranformer Room Control And Monitoring System, Stairwell Pressurization Control & Monitoring System', description2: 'Alveo High Park offers an inspiring new two-tower development in the master-planned, mixed-use city center of Quezon City. Located in the emerging enterprise capital of the North, High Park is an ideal location with prime access to business districts, medical and educational institutions, and major thoroughfares in the metro.'),
  Projects(proj_id: '5', title: 'Ayala Land Vermosa BLDG.', images: 'https://enyecontrols.com/ec_cpanel/images/projects/1622687669.jpg', category: '1', description1: 'Butterfly Valves And Actuators, Fan Coil Valves', description2: 'Ayala Land Vermosa is a 13-hectare regional mall that is strategically placed beside the Vermosa estate park and its principal terminal. Its retail facilities highlight health and sports-themed retail concept that are perfectly in tune with Vermosa spirit.'),
  Projects(proj_id: '6', title: 'Ayala Triangle Gardens', images: 'https://enyecontrols.com/ec_cpanel/images/projects/1622620781.jpg', category: '1', description1: 'Btu Meters, Energy Valve & Butterfly Valves & Actuators, Stairwell Pressurization Control & MonSensors And Transmitters, Damper Actuators, Differential Pressure Transmitters, Transformer Room Control And Monitoring System', description2: 'Ayala Triangle Gardens is a 2-hectare (4.9-acre) landscaped urban park. Inspired by Hyde Park in London, the park, which is dotted with palms, acacia trees, and tropical foliage, is considered as one of the few "green" areas in Makati.'),
  Projects(proj_id: '7', title: 'BA Lepanto Building', images: 'https://enyecontrols.com/ec_cpanel/images/projects/1622621124.jpg', category: '1', description1: '3 Way Motorize Globe Valves And Actuators', description2: 'BA Lepanto Building is a 20-storey structure with a typical floor plate of 1,025 sqm. per floor, with 2 basement parking levels, and has 8 elevators.'),
  Projects(proj_id: '8', title: 'BDO Tower', images: 'https://enyecontrols.com/ec_cpanel/images/projects/1622621376.jpg', category: '1', description1: 'Variable Air Volume Control And Monitoring System', description2: 'BDO Tower is a sleek 47 storey high-rise with a cross-shaped, symmetrical plan, which provides a maximum number of corner office spaces overlooking the Ortigas and ADB district.'),
  Projects(proj_id: '9', title: 'Makati Medical Center', images: 'https://www.enyecontrols.com/ec_cpanel/images/projects/1622617365.jpg', category: '2', description1: 'Fcu Controller, Smoke Extraction Control & Monitoring System, Ahu Control & Monitoring System', description2: 'Makati Medical Center leading healthcare facility in the Philippines, is a 609-bed tertiary hospital that provides sophisticated medical and surgical facilities. They are committed to delivering total quality healthcare services that exceed your expectations.'),
  Projects(proj_id: '10', title: 'Qualimed Iloilo', images: 'https://www.enyecontrols.com/ec_cpanel/images/projects/1622615816.jpg', category: '2', description1: 'Fire & Smoke Damper Actuators', description2: 'QualiMed is envisioned to be a nationwide network of healthcare facilities composed of mall-based clinics, ambulatory surgery centers, and full-service hospitals located in various parts of the country.'),
  Projects(proj_id: '11', title: 'Alveo Park Triangle', images: 'https://www.enyecontrols.com/ec_cpanel/images/projects/1622602748.jpg', category: '3', description1: 'Stairwell Pressurization Control & Monitoring System', description2: 'Alveo Park Triangle is a single-tower with a 49-story residential unit that will be one of Alveo Land’s most iconic residential condominium buildings and will help foster the company as one of the most high-end brands in the country.'),
  Projects(proj_id: '12', title: 'Avida Towers Asten 3', images: 'https://www.enyecontrols.com/ec_cpanel/images/projects/1622602886.jpg', category: '3', description1: 'Stairwell Pressurization Control & Monitoring System', description2: 'Avida Towers Asten 3 is a 10,000 square meter development located along Yakal and Malugay streets. Suited to the dynamic lifestyle of the young savvy achievers, it offers a wide range of retail and dining choices, creating a unique place of convergence.'),
  Projects(proj_id: '13', title: 'Solaire Resort & Casino', images: 'https://www.enyecontrols.com/ec_cpanel/images/projects/1622601563.jpg', category: '4', description1: 'Variable Air Volume Control & Monitoring System, Thermostatic Valves & Motorized Valves', description2: 'Solaire Resort & Casino is an iconic structure known for its discreet luxury, and undeniable class, and sophistication. Its modern design and silhouette bring together Manilas rich heritage and contemporary architecture that create the perfect canvas for the famous Manila Bay sunset to be put on display. '),
  Projects(proj_id: '14', title: 'Bicol International Airport', images: 'https://www.enyecontrols.com/ec_cpanel/images/projects/1622616710.jpg', category: '5', description1: 'Variable Air Volume Control & Monitoring System Bacnet Ready', description2: 'Bicol International Airport (BIA) is a new international airport envisioned to be the new gateway to the Bicol region.'),
  Projects(proj_id: '15', title: 'Abreeza Mall', images: 'https://www.enyecontrols.com/ec_cpanel/images/projects/1622592999.jpg', category: '6', description1: 'Stairwell Pressurization Control & Monitoring System Fire & Smoke Damper Actuators Stepdown Transformer W/ Cover & Foot Mounted', description2: 'Abreeza Mall is a large shopping mall complex located in Davao City, Philippines. It is the first Ayala Shopping Center located in Mindanao.'),
  Projects(proj_id: '16', title: 'De La Salle University Manila', images: 'https://www.enyecontrols.com/ec_cpanel/images/projects/1622680804.jpg', category: '7', description1: 'Globe Valve & Actuator', description2: 'DE LA SALLE is a hub for higher education training renowned for its academic excellence, prolific and relevant research, and involved community service. Nestled in the heart of Manila, De La Salle University is home to local and international students seeking quality education for a brighter future ahead.'),
  Projects(proj_id: '17', title: 'Robinsons Place Valencia', images: 'https://www.enyecontrols.com/ec_cpanel/images/projects/1622594983.jpg', category: '6', description1: 'Stairwell Pressurization Control & Monitoring System', description2: 'Robinsons Place Valencia is a three-level full-service shopping mall located in Valencia City, Bukidnon. The mall opened on December 12,2018.Robinsons Place Valencia is the first national brand mall in the province of Bukidnon, the 51st Robinsons mall in the country, and the seventh Robinsons mall in Mindanao.'),
  Projects(proj_id: '18', title: 'Mactan-Cebu International Airport', images: 'https://www.enyecontrols.com/ec_cpanel/images/projects/1622617300.jpg', category: '5', description1: 'Motorized Valves And Actuators', description2: 'Mactan-Cebu International Airport second busiest airport in the Philippines. The airport has a single runway, which is 3,300m long and paved with concrete and asphalt.'),
  Projects(proj_id: '19', title: 'Savoy Hotel', images: 'https://www.enyecontrols.com/ec_cpanel/images/projects/1622612456.jpg', category: '4', description1: 'Carbon Monoxide Control & Monitoring System', description2: 'Savoy Cebu 12-minute walk from the Lapu-Lapu shrine, a 20-m tall bronze statue, this casual hotel among shops and residential buildings is 2 km from the nearest beach and 8 km from Mactan-Cebu International Airport.'),
  Projects(proj_id: '20', title: 'St. Giles Makati', images: 'https://www.enyecontrols.com/ec_cpanel/images/projects/1622614284.jpeg', category: '4', description1: 'Fan Coil Valves And Actuators', description2: 'St. Giles Makati In the Makati Central Business District, this upscale hotel is 8 km from both the SM Mall of Asia and the National Museum of the Philippines and 9 km from Manila Ocean Park.'),
];