/// Flutter icons Dashboardicon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Dashboardicon
///      fonts:
///       - asset: fonts/Dashboardicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Dashboardicon {
  Dashboardicon._();

  static const _kFontFam = 'Dashboardicon';
  static const String? _kFontPkg = null;

  static const IconData projects_nav = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_us_nav = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_nav = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData systems_nav = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
