// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlus9OxOYGa-O54JL14qNQ84RCC0ke40Y',
    appId: '1:992119846808:android:076cfce1964f8eae751ded',
    messagingSenderId: '992119846808',
    projectId: 'enyecontrols-c9eda',
    storageBucket: 'enyecontrols-c9eda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMmP1AZjwalvfcRE--YkCGxLRn1XJiT1A',
    appId: '1:992119846808:ios:ffa0774c77b21ea3751ded',
    messagingSenderId: '992119846808',
    projectId: 'enyecontrols-c9eda',
    storageBucket: 'enyecontrols-c9eda.appspot.com',
    androidClientId: '992119846808-oh6a1b7jg2uvbj28qdvennanv7v4cl61.apps.googleusercontent.com',
    iosClientId: '992119846808-ui21nq5pb4taijq0bqo8buqj6b8ln0g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.enye',
  );
}
