import 'package:equatable/equatable.dart';

class Product extends Equatable{
  final String name;
  final String category;
  final String subcategory;
  final String imageUrl;
  final double price;
  final bool isRecommended;
  final bool isPopular;

  const Product ({
    required this.name,
    required this.category,
    required this.subcategory,
    required this.imageUrl,
    required this.price,
    required this.isPopular,
    required this.isRecommended,

});



  @override
  List<Object?> get props => [name, category, subcategory, imageUrl, price, isRecommended, isPopular];

  static List<Product> products = [
    Product(
        name: 'Accesories',
        category: 'Accesories',
        subcategory: 'Vector1',
        imageUrl: 'assets/products_category/categ1.png',
        price: 24.12,
        isRecommended: true,
        isPopular: true,
    ),
    Product(
      name: 'Accesories2',
      category: 'Accesories',
      subcategory: 'Vector',
      imageUrl: 'assets/products_category/categ1.png',
      price: 24.12,
      isRecommended: true,
      isPopular: true,
    ),
    Product(
      name: 'Accesories3',
      category: 'Accesories',
      subcategory: 'Vector1',
      imageUrl: 'assets/products_category/categ1.png',
      price: 24.12,
      isRecommended: true,
      isPopular: true,
    ),
    Product(
        name: 'Air Release Valve',
        category: 'Air Release Valve',
        subcategory: 'Vector1',
        imageUrl: 'assets/products_category/categ2.png',
        price: 24.12,
        isRecommended: false,
        isPopular: true,
    ),
    Product(
      name: 'Air Release Valve1',
      category: 'Air Release Valve',
      subcategory: 'Vector2',
      imageUrl: 'assets/products_category/categ2.png',
      price: 24.12,
      isRecommended: false,
      isPopular: true,
    ),
    Product(
        name: 'Automatic Control Valve',
        category: 'Automatic Control Valve',
        subcategory: 'Vector2',
        imageUrl: 'assets/products_category/categ3.png',
        price: 24.12,
        isRecommended: false,
        isPopular: false,
    ),
    Product(
        name: 'Backflow Preventer',
        category: 'Backflow Preventer',
        subcategory: 'Vector2',
        imageUrl: 'assets/products_category/categ4.png',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
        name: 'Balancing Valves',
        category: 'Balancing Valves',
        subcategory: 'Vector',
        imageUrl: 'assets/products_category/categ5.png',
        price: 24.12,
        isRecommended: false,
        isPopular: false,
    ),
    Product(
        name: 'Ball Valves',
        category: 'Ball Valves',
        subcategory: 'Vector3',
        imageUrl: 'assets/products_category/categ6.png',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
        name: 'Check Valve',
        category: 'Check Valve',
        subcategory: 'Vector3',
        imageUrl: 'assets/products_category/categ7.png',
        price: 24.12,
        isRecommended: true,
        isPopular: true,
    ),
    Product(
        name: 'Concentric Butterfly Valve',
        category: 'Concentric Butterfly Valve',
        subcategory: 'Vector3',
        imageUrl: 'assets/products_category/categ8.png',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
        name: 'Controller',
        category: 'Controller',
        subcategory: 'Vector4',
        imageUrl: 'assets/products_category/categ9.png',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
        name: 'Ecentric Butterfly Valves',
        category: 'Ecentric Butterfly Valves',
        subcategory: 'Vector4',
        imageUrl: 'assets/products_category/categ10.png',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
        name: 'Enye Controls Motorized Valves and Actuators',
        category: 'Enye Controls Motorized Valves and Actuators',
        subcategory: 'Vector4',
        imageUrl: 'assets/products_category/categ11.png',
        price: 24.12,
        isRecommended: false,
        isPopular: false,
    ),
    Product(
        name: 'Flexible Joint',
        category: 'Flexible Joint',
        subcategory: 'Vector',
        imageUrl: 'assets/products_category/categ12.png',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
        name: 'Gate Valve',
        category: 'Gate Valve',
        subcategory: 'Vector4',
        imageUrl: 'assets/products_category/categ13.png',
        price: 24.12,
        isRecommended: false,
        isPopular: true,
    ),
    Product(
        name: 'Globe Valve',
        category: 'Globe Valve',
        subcategory: 'Vector1',
        imageUrl: 'assets/products_category/categ14.png',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
        name: 'Flanger Valve',
        category: 'Flanger Valve',
        subcategory: 'Vector2',
        imageUrl: 'assets/products_category/categ15.png',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
        name: 'Softwares',
        category: 'Softwares',
        subcategory: 'Vector',
        imageUrl: 'assets/products_category/categ17.png',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
        name: 'Strainer',
        category: 'Strainer',
        subcategory: 'Vector3',
        imageUrl: 'assets/products_category/categ18.png',
        price: 24.12,
        isRecommended: true,
        isPopular: true,
    ),
    Product(
        name: 'Test Equipments',
        category: 'Test Equipments',
        subcategory: 'Vector2',
        imageUrl: 'assets/products_category/categ19.png',
        price: 24.12,
        isRecommended: false,
        isPopular: false,
    ),
    Product(
        name: 'Variable Frequency Drive',
        category: 'Variable Frequency Drive',
        subcategory: 'Vector',
        imageUrl: 'assets/products_category/categ20.png',
        price: 24.12,
        isRecommended: true,
        isPopular: true,
    ),
    Product(
        name: 'Water Meter',
        category: 'Water Meter',
        subcategory: 'Vector4',
        imageUrl: 'assets/products_category/categ21.png',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
];
}