import 'package:equatable/equatable.dart';

class Product extends Equatable{
  final String name;
  final String category;
  final String subcategory;
  final String imageUrl;
  final double price;
  final bool isRecommended;
  final bool isPopular;

  const Product ({
    required this.name,
    required this.category,
    required this.subcategory,
    required this.imageUrl,
    required this.price,
    required this.isPopular,
    required this.isRecommended,

});



  @override
  List<Object?> get props => [name, category, subcategory, imageUrl, price, isRecommended, isPopular];

  static List<Product> products = [
    Product(
        name: 'Gateways',
        category: 'Accesories',
        subcategory: 'Vector Accesories',
        imageUrl: 'assets/producs_image/accessories/vector/vector1.jpg',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
      name: 'Controllers and Sensors',
      category: 'Accesories',
      subcategory: 'Vector Accesories',
      imageUrl: 'assets/producs_image/accessories/vector/vector2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Connecting Box Mounting',
      category: 'Accesories',
      subcategory: 'Vector Accesories',
      imageUrl: 'assets/producs_image/accessories/vector/vector3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Memory and Plug-ins',
      category: 'Accesories',
      subcategory: 'Vector Accesories',
      imageUrl: 'assets/producs_image/accessories/vector/vector4.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Panel Mounting Kit',
      category: 'Accesories',
      subcategory: 'Vector Accesories',
      imageUrl: 'assets/producs_image/accessories/vector/vector5.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'AMF-Series',
      category: 'Accesories',
      subcategory: 'Vector Accesories',
      imageUrl: 'assets/producs_image/accessories/vector/vector6.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'AMC-Series',
      category: 'Accesories',
      subcategory: 'Vector Accesories',
      imageUrl: 'assets/producs_image/accessories/vector/vector7.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Weather Shield',
      category: 'Accesories',
      subcategory: 'Vector Accesories',
      imageUrl: 'assets/producs_image/accessories/vector/vector8.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),


    Product(
      name: 'Plugs and Plugin Terminal',
      category: 'Accesories',
      subcategory: 'Plugs and Plugin Terminal',
      imageUrl: 'assets/products_category/categ1.png',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),



    Product(
      name: 'Other Accessories',
      category: 'Accesories',
      subcategory: 'Other Accessories',
      imageUrl: 'assets/producs_image/accessories/other_accesories/Other1.png',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),




    Product(
        name: 'AVMX series Air Release Valve',
        category: 'Air Release Valve',
        subcategory: 'Air Release Valve',
        imageUrl: 'assets/producs_image/air_release/air/air1.jpg',
        price: 24.12,
        isRecommended: false,
        isPopular: true,
    ),
    Product(
      name: 'AVRX Series Air Release Valve',
      category: 'Air Release Valve',
      subcategory: 'Air Release Valve',
      imageUrl: 'assets/producs_image/air_release/air/air2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: true,
    ),
    Product(
      name: 'AVAX Series Brass Air Release Valve',
      category: 'Air Release Valve',
      subcategory: 'Brass Air Release Valve',
      imageUrl: 'assets/producs_image/air_release/brass_air/brassAir.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: true,
    ),



    Product(
        name: 'PRYS Series SS Pressure Reducing Valve',
        category: 'Automatic Control Valve',
        subcategory: 'Pressure Reducing Valve',
        imageUrl: 'assets/producs_image/automatic_control/reducing/pressure1.jpg',
        price: 24.12,
        isRecommended: false,
        isPopular: false,
    ),
    Product(
      name: 'A200 ACV Series Pressure Reducing Valve',
      category: 'Automatic Control Valve',
      subcategory: 'Pressure Reducing Valve',
      imageUrl: 'assets/producs_image/automatic_control/reducing/pressure2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'A100 ACV Series Floating Valve',
      category: 'Automatic Control Valve',
      subcategory: 'Floating Valve',
      imageUrl: 'assets/producs_image/automatic_control/floating/floating.png',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'A300 Series Slow-closure Type Check Valve',
      category: 'Automatic Control Valve',
      subcategory: 'Check Valve',
      imageUrl: 'assets/producs_image/automatic_control/check/check.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'A500 Series Pressure Relief Valve',
      category: 'Automatic Control Valve',
      subcategory: 'Pressure Relief Valve',
      imageUrl: 'assets/producs_image/automatic_control/relief/pressureRelief.png',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),



    Product(
        name: 'BCVBP Series Backflow Preventers',
        category: 'Backflow Preventer',
        subcategory: 'Backflow Preventer',
        imageUrl: 'assets/producs_image/backflow_preventer/backflow/backflow.jpg',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),


    Product(
        name: 'Alpha Threaded',
        category: 'Balancing Valves',
        subcategory: 'Valves',
        imageUrl: 'assets/producs_image/balancing/valves/valves1.jpg',
        price: 24.12,
        isRecommended: false,
        isPopular: false,
    ),
    Product(
      name: 'Alpha Wafer',
      category: 'Balancing Valves',
      subcategory: 'Valves',
      imageUrl: 'assets/producs_image/balancing/valves/valves2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Alpha Cartridges',
      category: 'Balancing Valves',
      subcategory: 'Cartridges',
      imageUrl: 'assets/producs_image/balancing/cartridges/cartridges1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Alpha Cool Cartridges',
      category: 'Balancing Valves',
      subcategory: 'Cartridges',
      imageUrl: 'assets/producs_image/balancing/cartridges/cartridges2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Pressure Independent Control Valve',
      category: 'Balancing Valves',
      subcategory: 'Pressure Independent Control Valve',
      imageUrl: 'assets/producs_image/balancing/pressure_control/pcontrol1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Pressure Independent Control Valve 50-300',
      category: 'Balancing Valves',
      subcategory: 'Pressure Independent Control Valve',
      imageUrl: 'assets/producs_image/balancing/pressure_control/pcontrol2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),


    Product(
        name: 'BABV Series Brass Ball Valves',
        category: 'Ball Valves',
        subcategory: 'Brass Ball Valves',
        imageUrl: 'assets/producs_image/ball/brass/ball1.jpg',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
      name: 'BLBV Series Lead Free Brass Ball Valve',
      category: 'Ball Valves',
      subcategory: 'Brass Ball Valves',
      imageUrl: 'assets/producs_image/ball/brass/ball2.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'BRBV Series Bronze Ball Valves',
      category: 'Ball Valves',
      subcategory: 'Bronze Ball Valves',
      imageUrl: 'assets/producs_image/ball/bronze/bronze1.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'BABH Series Long Neck Ball Valve',
      category: 'Ball Valves',
      subcategory: 'Long Neck Ball Valves',
      imageUrl: 'assets/producs_image/ball/long/long1.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),


    Product(
        name: 'BACV Series Brass Swing Check Valves',
        category: 'Check Valve',
        subcategory: 'Swing Check Valve',
        imageUrl: 'assets/producs_image/check/swing/swing1.jpg',
        price: 24.12,
        isRecommended: true,
        isPopular: true,
    ),
    Product(
      name: 'BRCV Series Bronze Swing Check Valves',
      category: 'Check Valve',
      subcategory: 'Swing Check Valve',
      imageUrl: 'assets/producs_image/check/swing/swing2.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: true,
    ),
    Product(
      name: 'CVSF Series Flex Swing Check Valve',
      category: 'Check Valve',
      subcategory: 'Swing Check Valve',
      imageUrl: 'assets/producs_image/check/swing/swing3.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: true,
    ),
    Product(
      name: 'BRVB Series Spring Load Check Valve',
      category: 'Check Valve',
      subcategory: 'Spring Load Check Valve',
      imageUrl: 'assets/producs_image/check/spring/spring1.png',
      price: 24.12,
      isRecommended: true,
      isPopular: true,
    ),
    Product(
      name: 'CVDD Series Dual Plates Check Valve',
      category: 'Check Valve',
      subcategory: 'Dual Plates Check Valve',
      imageUrl: 'assets/producs_image/check/dual/dual.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: true,
    ),



    Product(
        name: 'BWLX Series Wafer Butterfly Valve Wafer Concentric Disc',
        category: 'Concentric Butterfly Valve',
        subcategory: 'Wafer Butterfly Valve ',
        imageUrl: 'assets/producs_image/concentric/wafer/wafer1.jpg',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
      name: 'BWGX Series Wafer Butterfly Valve Wafer Concentric Disc',
      category: 'Concentric Butterfly Valve',
      subcategory: 'Wafer Butterfly Valve ',
      imageUrl: 'assets/producs_image/concentric/wafer/wafer2.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'BWGE Series Wafer Butterfly Valve (Epoxy Coated Disc)',
      category: 'Concentric Butterfly Valve',
      subcategory: 'Wafer Butterfly Valve ',
      imageUrl: 'assets/producs_image/concentric/wafer/wafer3.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'BWTX ON/OFF BWAX Modulating Electric Actuator Butterfly Valve',
      category: 'Concentric Butterfly Valve',
      subcategory: 'Electric Actuator Butterfly Valve',
      imageUrl: 'assets/producs_image/concentric/electric/electric1.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'BWTE ON/OFF BWAE Modulating Electric Actuator Butterfly Valve (Epoxy Coated Disc)',
      category: 'Concentric Butterfly Valve',
      subcategory: 'Electric Actuator Butterfly Valve',
      imageUrl: 'assets/producs_image/concentric/electric/electric2.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'BZTX ON/OFF BZAX Modulating Electric Actuator Butterfly Valve',
      category: 'Concentric Butterfly Valve',
      subcategory: 'Electric Actuator Butterfly Valve',
      imageUrl: 'assets/producs_image/concentric/electric/electric3.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'BLLX Series Lug Butterfly Valve',
      category: 'Concentric Butterfly Valve',
      subcategory: 'Lug Butterfly Valve',
      imageUrl: 'assets/producs_image/concentric/lug/lug1.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'BLGX Series Lug Butterfly Valve',
      category: 'Concentric Butterfly Valve',
      subcategory: 'Lug Butterfly Valve',
      imageUrl: 'assets/producs_image/concentric/lug/lug2.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'BZLX Series Butterfly Valve Flanged Concentric Disc',
      category: 'Concentric Butterfly Valve',
      subcategory: 'Flanged Concentric Disc',
      imageUrl: 'assets/producs_image/concentric/flanged_disc/disc1.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'BZGX Series Butterfly Valve Flanged Concentric Type',
      category: 'Concentric Butterfly Valve',
      subcategory: 'Flanged Concentric Type',
      imageUrl: 'assets/producs_image/concentric/flanged_type/type1.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'BZGE Series Butterfly Valve Flanged Concentric Type (Epoxy Coated Disc)',
      category: 'Concentric Butterfly Valve',
      subcategory: 'Flanged Concentric Type',
      imageUrl: 'assets/producs_image/concentric/flanged_type/type2.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'BWSX Series Fire Protection Signal Feedback Butterfly Valve with Supervisor Switch',
      category: 'Concentric Butterfly Valve',
      subcategory: 'Fire Protection Signal Feedback Butterfly Valve',
      imageUrl: 'assets/producs_image/concentric/feedback/feedback1.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),


    Product(
        name: 'Innotech OMNI',
        category: 'Controller',
        subcategory: 'Omni BEMS Controllers',
        imageUrl: 'assets/producs_image/controller/omni/omni1.jpg',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
      name: 'Omni Compact',
      category: 'Controller',
      subcategory: 'Omni BEMS Controllers',
      imageUrl: 'assets/producs_image/controller/omni/omni2.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'Omni U10',
      category: 'Controller',
      subcategory: 'Omni BEMS Controllers',
      imageUrl: 'assets/producs_image/controller/omni/omni3.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'Universal Programmable Controller',
      category: 'Controller',
      subcategory: 'Universal Programmable Controller',
      imageUrl: 'assets/producs_image/controller/universal/universal.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'Intelligent Fan Coil Controller',
      category: 'Controller',
      subcategory: 'Intelligent Controller',
      imageUrl: 'assets/producs_image/controller/intelligent/intelligent1.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'Fan Coil Controller with Modbus RTU',
      category: 'Controller',
      subcategory: 'Intelligent Controller',
      imageUrl: 'assets/producs_image/controller/intelligent/intelligent2.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'Wall-mounted Controller and Sensor',
      category: 'Controller',
      subcategory: 'Intelligent Controller',
      imageUrl: 'assets/producs_image/controller/intelligent/intelligent3.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),




    Product(
        name: 'BFGX Series Butterfly Valve',
        category: 'Ecentric Butterfly Valves',
        subcategory: 'Butterfly Valve',
        imageUrl: 'assets/producs_image/eccentric/butterfly/butterfly1.jpg',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
      name: 'BFTX Series Motorized Butterfly Valve',
      category: 'Ecentric Butterfly Valves',
      subcategory: 'Motorized Butterfly Valve',
      imageUrl: 'assets/producs_image/eccentric/motorized/motorized1.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'BFPX Series Pneumatic Butterfly Valve',
      category: 'Ecentric Butterfly Valves',
      subcategory: 'Pneumatic Butterfly Valve',
      imageUrl: 'assets/producs_image/eccentric/pneumatic/pneumatic.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),


    Product(
        name: 'Torque 2 Nm - ECCA Series Standard Damper Actuator',
        category: 'Enye Controls Motorized Valves and Actuators',
        subcategory: 'Damper Actuator',
        imageUrl: 'assets/producs_image/actuators/damper/damper1.jpg',
        price: 24.12,
        isRecommended: false,
        isPopular: false,
    ),
    Product(
      name: 'Torque 5 Nm - ECCA Series Standard Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/damper/damper2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 10 Nm - ECCA Series Standard Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/damper/damper3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 20 Nm - ECCA Series Standard Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/damper/damper4.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 40 Nm - ECCA Series Standard Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/damper/damper5.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 2 Nm - ECCM Series Standard Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/damper/damper6.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 5 Nm - ECCM Series Standard Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/damper/damper7.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 10 Nm - ECCM Series Standard Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/damper/damper8.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 40 Nm - ECCM Series Standard Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/damper/damper9.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 20 Nm - ECCM Series Standard Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/damper/damper10.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 10 Nm - ECSA Series Fast Running Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/damper/damper11.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 20 Nm - ECSA Series Fast Running Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/damper/damper12.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 5 Nm - ECFA Series Spring Return Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Spring Return Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/spring/spring1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 3 Nm - ECFA Series Spring Return Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Series Spring Return Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/spring/spring2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 8 Nm - ECFA Series Spring Return Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Series Spring Return Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/spring/spring3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 20 Nm - ECFA Series Spring Return Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Series Spring Return Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/spring/spring4.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 5 Nm - EECM Series Electronic Return Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Electronic Return Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/electronic/electronic1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 10 Nm - EECM Series Electronic Return Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Electronic Return Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/electronic/electronic2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 20 Nm - EECM Series Electronic Return Damper Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Electronic Return Damper Actuator',
      imageUrl: 'assets/producs_image/actuators/electronic/electronic1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 5Nm - ECBA Series Ball Valve Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Ball Valve Actuator',
      imageUrl: 'assets/producs_image/actuators/ball/ball1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 5Nm - ECBA Series Ball Valve Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Ball Valve Actuator',
      imageUrl: 'assets/producs_image/actuators/ball/ball2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 10Nm - ECBA Series Ball Valve Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Ball Valve Actuator',
      imageUrl: 'assets/producs_image/actuators/ball/ball3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 5Nm - ECBM Series Ball Valve Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Ball Valve Actuator',
      imageUrl: 'assets/producs_image/actuators/ball/ball4.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Torque 10Nm - ECBM Series Ball Valve Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Ball Valve Actuator',
      imageUrl: 'assets/producs_image/actuators/ball/ball1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'EVCB 7000 SERIES CHARACTERIZED DISC BALL VALVE',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Characteized Disc Ball Valve',
      imageUrl: 'assets/producs_image/actuators/characterized/characterized1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'EVCB 9000 SERIES CHARACTERIZED DISC BALL VALVE',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Characteized Disc Ball Valve',
      imageUrl: 'assets/producs_image/actuators/characterized/characterized1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'ECMB SERIES MOTORIZED FAN COIL VALVE',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Motorized Fan Coil Valve',
      imageUrl: 'assets/producs_image/actuators/motorized/motorized1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'EVBF Series Butterfly Valve',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Butterfly Valve',
      imageUrl: 'assets/producs_image/actuators/butterfly/butterfly.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'ECY Series Butterfly Valve Actuator',
      category: 'Enye Controls Motorized Valves and Actuators',
      subcategory: 'Butterfly Valve',
      imageUrl: 'assets/producs_image/actuators/butterfly/butterfly2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),




    Product(
        name: 'S10 Series Rubber Flexible Joint PN16 Flanged Single Ball Type',
        category: 'Flexible Joint',
        subcategory: 'Rubber Flexible Joint',
        imageUrl: 'assets/producs_image/flexible/expansion/expansion1.jpg',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
      name: 'S30 Series Rubber Expansion Joint PN10 Thread Double Ball Type',
      category: 'Flexible Joint',
      subcategory: 'Rubber Expansion Joint',
      imageUrl: 'assets/producs_image/flexible/rubber/rubber1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'L-120 Series SS Expansion Joint',
      category: 'Flexible Joint',
      subcategory: 'SS Expansion Joint',
      imageUrl: 'assets/producs_image/flexible/rubber/rubber2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),


    Product(
        name: 'BAGV Series Brass Gate Valve',
        category: 'Gate Valve',
        subcategory: 'Brass Gate Valve',
        imageUrl: 'assets/producs_image/gate/brass/brass1.jpg',
        price: 24.12,
        isRecommended: false,
        isPopular: false,
    ),
    Product(
      name: 'BLGV Series Lead Free Brass Gate Valve',
      category: 'Gate Valve',
      subcategory: 'Brass Gate Valve',
      imageUrl: 'assets/producs_image/gate/brass/brass2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'BRGV Series Bronze Gate Valve',
      category: 'Gate Valve',
      subcategory: 'Bronze Gate Valve',
      imageUrl: 'assets/producs_image/gate/bronze/bronze1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'BAGB Series Brass Lockable Gate Valve',
      category: 'Gate Valve',
      subcategory: 'Lockable Gate Valve',
      imageUrl: 'assets/producs_image/gate/lockable/lockable1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'BLGB Series Brass Lockable Lead Free Gate Valve',
      category: 'Gate Valve',
      subcategory: 'Lockable Gate Valve',
      imageUrl: 'assets/producs_image/gate/lockable/lockable2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'RVLX Series Lockable NRS Gate Valve',
      category: 'Gate Valve',
      subcategory: 'Lockable Gate Valve',
      imageUrl: 'assets/producs_image/gate/lockable/lockable3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'BAGS Series Extension Length Gate Valve',
      category: 'Gate Valve',
      subcategory: 'Extension Length Gate Valve',
      imageUrl: 'assets/producs_image/gate/extension/extension.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'RVHX Series NRS Gate Valve PN16 Flanged Resilient Seated BS5163 Type',
      category: 'Gate Valve',
      subcategory: 'PN16 Flanged Resilient Seated Gate Valve',
      imageUrl: 'assets/producs_image/gate/flanged/flanged1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'RVHX F4 Series NRS Gate Valve PN16 Flanged Resilent Seated DIN3202 F4 type',
      category: 'Gate Valve',
      subcategory: 'PN16 Flanged Resilient Seated Gate Valve',
      imageUrl: 'assets/producs_image/gate/flanged/flanged2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: true,
    ),
    Product(
      name: 'RVRX OS&Y Gate Valve PN16 Flanged Resilient Seated EN1171 Type',
      category: 'Gate Valve',
      subcategory: 'PN16 Flanged Resilient Seated Gate Valve',
      imageUrl: 'assets/producs_image/gate/flanged/flanged3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'RVCX Series Stem Cap Gate Valve',
      category: 'Gate Valve',
      subcategory: 'Stem Cap Gate Valve',
      imageUrl: 'assets/producs_image/gate/stem/stem1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'RVGZ Series Spigot Gate Valve',
      category: 'Gate Valve',
      subcategory: 'Spigot Gate Valve',
      imageUrl: 'assets/producs_image/gate/spigot/spigot.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: true,
    ),
    Product(
      name: 'RVSX Series Fire Protection Signal Feedback Gate Valve',
      category: 'Gate Valve',
      subcategory: 'Fire Protection Signal Feedback Gate Valve',
      imageUrl: 'assets/producs_image/gate/fire/fire.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),




    Product(
        name: 'BAGL Series Brass Globe Valve',
        category: 'Globe Valve',
        subcategory: 'Brass Globe Valve',
        imageUrl: 'assets/producs_image/globe/brass/brass.jpg',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
      name: 'BRGL Series Bronze Globe Valves',
      category: 'Globe Valve',
      subcategory: 'Broze Globe Valve',
      imageUrl: 'assets/producs_image/globe/bronze/bronze.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),



    Product(
        name: 'FCEX Plunger Valve',
        category: 'Plunger Valve',
        subcategory: 'Plunger Valve',
        imageUrl: 'assets/producs_image/plunger/plunger1.jpg',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),



    Product(
        name: 'Genesis II Software',
        category: 'Softwares',
        subcategory: 'Software and Utilities',
        imageUrl: 'assets/producs_image/softwares/softwares/softwares1.jpg',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
      name: 'Magellan Software',
      category: 'Softwares',
      subcategory: 'Software and Utilities',
      imageUrl: 'assets/producs_image/softwares/softwares/softwares2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),



    Product(
        name: 'BAYS Series Brass Y-Strainers',
        category: 'Strainer',
        subcategory: 'Y Strainers',
        imageUrl: 'assets/producs_image/strainers/ystrainer/strainer1.jpg',
        price: 24.12,
        isRecommended: false,
        isPopular: false,
    ),
    Product(
      name: 'BRYS Series Bronze Y Strainers',
      category: 'Strainer',
      subcategory: 'Vector3',
      imageUrl: 'assets/producs_image/strainers/ystrainer/strainer2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'YSTF Series Y Strainer',
      category: 'Strainer',
      subcategory: 'Y Strainer',
      imageUrl: 'assets/producs_image/strainers/ystrainer/strainer3.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
    Product(
      name: 'YSAX Suction Diffuser',
      category: 'Strainer',
      subcategory: 'Suction Diffuser',
      imageUrl: 'assets/producs_image/strainers/suction/suction1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: true,
    ),
    Product(
      name: 'YSTA Series Basket Strainers',
      category: 'Strainer',
      subcategory: 'Basket Strainers',
      imageUrl: 'assets/producs_image/strainers/basket/basket1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),



    Product(
        name: '100MM Vane Thermo-Anemometer Test Instrument',
        category: 'Test Equipments',
        subcategory: 'Thermo-Anemometer',
        imageUrl: 'assets/producs_image/test/thermo/thermo1.jpg',
        price: 24.12,
        isRecommended: false,
        isPopular: false,
    ),
    Product(
      name: 'Thermo-Anemometer Probe',
      category: 'Test Equipments',
      subcategory: 'Thermo-Anemometer',
      imageUrl: 'assets/producs_image/test/thermo/thermo2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: '100mm Vane Thermo-Anemometer Probe',
      category: 'Test Equipments',
      subcategory: 'Thermo-Anemometer',
      imageUrl: 'assets/producs_image/test/thermo/thermo3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Thermo-Anemometer Test Instrument',
      category: 'Test Equipments',
      subcategory: 'Thermo-Anemometer',
      imageUrl: 'assets/producs_image/test/thermo/thermo4.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Air Velocity Meter',
      category: 'Test Equipments',
      subcategory: 'Air Meter',
      imageUrl: 'assets/producs_image/test/air/air1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Air Meter / Draft Gage',
      category: 'Test Equipments',
      subcategory: 'Air Meter',
      imageUrl: 'assets/producs_image/test/air/air2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Averaging Air Flow Grid',
      category: 'Test Equipments',
      subcategory: 'Air Meter',
      imageUrl: 'assets/producs_image/test/air/air3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Handheld Indoor Air Quality Meter',
      category: 'Test Equipments',
      subcategory: 'Air Meter',
      imageUrl: 'assets/producs_image/test/air/air4.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Molded Plastic Air Velocity Meter',
      category: 'Test Equipments',
      subcategory: 'Air Meter',
      imageUrl: 'assets/producs_image/test/air/air5.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Air Velocity Kits',
      category: 'Test Equipments',
      subcategory: 'Test Kits',
      imageUrl: 'assets/producs_image/test/kits/kits1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Portable Ultrasonic Flowmeter Kit',
      category: 'Test Equipments',
      subcategory: 'Test Kits',
      imageUrl: 'assets/producs_image/test/kits/kits2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Hydronic Differential Pressure Meter Kit',
      category: 'Test Equipments',
      subcategory: 'Test Kits',
      imageUrl: 'assets/producs_image/test/kits/kits3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Test, Adjust, and Balance Kit',
      category: 'Test Equipments',
      subcategory: 'Test Kits',
      imageUrl: 'assets/producs_image/test/kits/kits4.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Gas Pressure Test Kit',
      category: 'Test Equipments',
      subcategory: 'Test Kits',
      imageUrl: 'assets/producs_image/test/kits/kits5.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Thermo-Hygrometer Probe',
      category: 'Test Equipments',
      subcategory: 'Thermo-Hygrometer',
      imageUrl: 'assets/producs_image/test/hygrometer/hygro1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Thermo-Hygrometer',
      category: 'Test Equipments',
      subcategory: 'Thermo-Hygrometer',
      imageUrl: 'assets/producs_image/test/hygrometer/hygro2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Current / Voltage Signal Generator',
      category: 'Test Equipments',
      subcategory: 'Signal Generator',
      imageUrl: 'assets/producs_image/test/signal/signal1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Analog Signal Generator',
      category: 'Test Equipments',
      subcategory: 'Signal Generator',
      imageUrl: 'assets/producs_image/test/signal/signal1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Button Data Logger',
      category: 'Test Equipments',
      subcategory: 'Data Logger',
      imageUrl: 'assets/producs_image/test/data/data1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'High Temperature Data Logger',
      category: 'Test Equipments',
      subcategory: 'Data Logger',
      imageUrl: 'assets/producs_image/test/data/data2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'LCD Pressure Data Logger',
      category: 'Test Equipments',
      subcategory: 'Data Logger',
      imageUrl: 'assets/producs_image/test/data/data3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Pressure/Temperature Data Logger',
      category: 'Test Equipments',
      subcategory: 'Data Logger',
      imageUrl: 'assets/producs_image/test/data/data4.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Wireless Wi-Fi Data Logger',
      category: 'Test Equipments',
      subcategory: 'Data Logger',
      imageUrl: 'assets/producs_image/test/data/data5.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Compact USB Data Logger',
      category: 'Test Equipments',
      subcategory: 'Data Logger',
      imageUrl: 'assets/producs_image/test/data/data6.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Calibration Pump',
      category: 'Test Equipments',
      subcategory: 'Pump',
      imageUrl: 'assets/producs_image/test/pump/pump1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Hand Pump',
      category: 'Test Equipments',
      subcategory: 'Pump',
      imageUrl: 'assets/producs_image/test/pump/pump2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Pneumatic Calibration Hand Pump',
      category: 'Test Equipments',
      subcategory: 'Pump',
      imageUrl: 'assets/producs_image/test/pump/pump3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Hydraulic Calibration Hand Pump',
      category: 'Test Equipments',
      subcategory: 'Pump',
      imageUrl: 'assets/producs_image/test/pump/pump4.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Low Pressure Calibration Pump',
      category: 'Test Equipments',
      subcategory: 'Pump',
      imageUrl: 'assets/producs_image/test/pump/pump5.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Pneumatic Hand Pump',
      category: 'Test Equipments',
      subcategory: 'Pump',
      imageUrl: 'assets/producs_image/test/pump/pump6.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Aspirator Bulb',
      category: 'Test Equipments',
      subcategory: 'Aspirator Bulb',
      imageUrl: 'assets/producs_image/test/aspirator/aspirator.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Differential Pressure Anemometer',
      category: 'Test Equipments',
      subcategory: 'Anemometer',
      imageUrl: 'assets/producs_image/test/anemometer/anemometer1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Vaneometer Swing Vane Anemometer',
      category: 'Test Equipments',
      subcategory: 'Anemometer',
      imageUrl: 'assets/producs_image/test/anemometer/anemometer2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Single Pressure and Differential Pressure Digital Manometer',
      category: 'Test Equipments',
      subcategory: 'Manometer',
      imageUrl: 'assets/producs_image/test/manometer/manometer.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Flex Tube U-tube Manometers',
      category: 'Test Equipments',
      subcategory: 'Manometer',
      imageUrl: 'assets/producs_image/test/manometer/manometer2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Gas Pressure Manometer',
      category: 'Test Equipments',
      subcategory: 'Manometer',
      imageUrl: 'assets/producs_image/test/manometer/manometer3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Precision Digital Pressure Manometer',
      category: 'Test Equipments',
      subcategory: 'Manometer',
      imageUrl: 'assets/producs_image/test/manometer/manometer4.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Precision Handheld Digital Manometer',
      category: 'Test Equipments',
      subcategory: 'Manometer',
      imageUrl: 'assets/producs_image/test/manometer/manometer5.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Intrinsically Safe Handheld Digital Manometer',
      category: 'Test Equipments',
      subcategory: 'Manometer',
      imageUrl: 'assets/producs_image/test/manometer/manometer6.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Handheld Digital Manometer',
      category: 'Test Equipments',
      subcategory: 'Manometer',
      imageUrl: 'assets/producs_image/test/manometer/manometer7.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Wireless Hydronic Differential Pressure Manometer',
      category: 'Test Equipments',
      subcategory: 'Manometer',
      imageUrl: 'assets/producs_image/test/manometer/manometer8.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Hydronic Differential Pressure Manometer',
      category: 'Test Equipments',
      subcategory: 'Manometer',
      imageUrl: 'assets/producs_image/test/manometer/manometer9.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Slack Tube Manometer',
      category: 'Test Equipments',
      subcategory: 'Manometer',
      imageUrl: 'assets/producs_image/test/manometer/manometer10.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Dual Range Flex-Tube U-Inclined Manometers',
      category: 'Test Equipments',
      subcategory: 'Manometer',
      imageUrl: 'assets/producs_image/test/manometer/manometer11.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Handheld Digital Manometer 477B',
      category: 'Test Equipments',
      subcategory: 'Manometer',
      imageUrl: 'assets/producs_image/test/manometer/manometer12.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),


    Product(
      name: 'Wireless Differential Pressure Module',
      category: 'Test Equipments',
      subcategory: 'Pressure Module',
      imageUrl: 'assets/producs_image/test/module/module1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Dual Input Thermocouple Thermometer',
      category: 'Test Equipments',
      subcategory: 'Thermometer',
      imageUrl: 'assets/producs_image/test/thermometer/thermometer.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Ellipsoidal Tip Pitot Tube',
      category: 'Test Equipments',
      subcategory: 'Pitot Tube',
      imageUrl: 'assets/producs_image/test/pitot/pitot1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: '“S” Type Stainless Steel Pitot Tubes',
      category: 'Test Equipments',
      subcategory: 'Pitot Tube',
      imageUrl: 'assets/producs_image/test/pitot/pitot2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Straight Stainless Steel Pitot Tube',
      category: 'Test Equipments',
      subcategory: 'Pitot Tube',
      imageUrl: 'assets/producs_image/test/pitot/pitot3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Telescoping Stainless Steel Pitot Tube',
      category: 'Test Equipments',
      subcategory: 'Pitot Tube',
      imageUrl: 'assets/producs_image/test/pitot/pitot4.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Stainless Steel Pitot Tube',
      category: 'Test Equipments',
      subcategory: 'Pitot Tube',
      imageUrl: 'assets/producs_image/test/pitot/pitot5.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Portable Digital Tachometer',
      category: 'Test Equipments',
      subcategory: 'Tachometer',
      imageUrl: 'assets/producs_image/test/tachometer/tachometer.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'SMART Air Hood Balancing Instrument',
      category: 'Test Equipments',
      subcategory: 'Balancing Instrument',
      imageUrl: 'assets/producs_image/test/instrument/instrument.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Portable Series Wind Meter',
      category: 'Test Equipments',
      subcategory: 'Wind Meter',
      imageUrl: 'assets/producs_image/test/wind/wind1.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Pocket Wind Meter',
      category: 'Test Equipments',
      subcategory: 'Wind Meter',
      imageUrl: 'assets/producs_image/test/wind/wind2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Wind Speed Indicator',
      category: 'Test Equipments',
      subcategory: 'Wind Meter',
      imageUrl: 'assets/producs_image/test/wind/wind3.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),




    Product(
        name: 'F510 Fan & Pump Drive',
        category: 'Variable Frequency Drive',
        subcategory: 'F510 Variable Frequency Drive',
        imageUrl: 'assets/producs_image/variable/variable/variable1.jpg',
        price: 24.12,
        isRecommended: false,
        isPopular: true,
    ),


    Product(
        name: 'RMT Series RS-485 / Modbus RTU',
        category: 'Water Meter',
        subcategory: 'Water Meter',
        imageUrl: 'assets/producs_image/water/water/water1.jpg',
        price: 24.12,
        isRecommended: true,
        isPopular: false,
    ),
    Product(
      name: 'Hybrid Digital Multi-Jet Water Meter',
      category: 'Water Meter',
      subcategory: 'Water Meter',
      imageUrl: 'assets/producs_image/water/water/water2.jpg',
      price: 24.12,
      isRecommended: false,
      isPopular: false,
    ),
    Product(
      name: 'Hybrid Digital Woltmann Water Meter',
      category: 'Water Meter',
      subcategory: 'Water Meter',
      imageUrl: 'assets/producs_image/water/water/water3.jpg',
      price: 24.12,
      isRecommended: true,
      isPopular: false,
    ),
];
}
