

import 'package:equatable/equatable.dart';

class ProductInfo extends Equatable{
  final String subcategory;
  final String name;
  final String model;
  final String size;
  final String price;


  const ProductInfo({
    required this.subcategory,
    required this.name,
    required this.model,
    required this.size,
    required this.price
});

  @override
  List<Object?> get props => [subcategory, name, model, size, price];
  static List<ProductInfo> info = [
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
    model: 'AEX-SMP-BAC',
    size: 'HMI/Server/Controller Atrius solution builder license included',
    price: '47,218.12',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'AEX-SMP-MOD',
      size: 'HMI/Server/Controller Atrius Solution Builder License included',
      price: '47,218.12',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'FXL-Dongle',
      size: 'BACnet MS/TP communication add-on for GSM-2000-SMP',
      price: '242,824.24',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'GSM-100-DSA',
      size: 'Basic license fee for Atrius Solution builder',
      price: '91,235.02',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'GSM-1000-BMX',
      size: 'MODBUS communication add-on for GSM-2000-SMP',
      price: '277,458.23',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'GSM-1000-DSA',
      size: 'Basic license fee for Atrius Solution builder',
      price: '258,830.39',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'GSM-1500-DSA',
      size: 'Basic license fee for Atrius Solution builder',
      price: '314,713.91',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'GSM-2000-SMP V2.0',
      size: 'HMI/Server/Controller Atrius Solution Builder License not included',
      price: '205,678.95',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'GSM-DSA',
      size: 'HMI/Server/Controller Atrius solution builder license included',
      price: '35,379.10',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'Kiosk/engineering',
      size: 'Annual maintenance fee type M',
      price: '55,855.92',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'Large',
      size: 'basic license fee for Atrius Solution builder',
      price: '1,117,284.04',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'Large',
      size: 'Annual maintenance fee type L',
      price: '167,595.37',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'Medium',
      size: 'Basic license fee for Atrius Solution builder',
      price: '558,642.02',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'Medium',
      size: 'Basic license fee for Atrius Solution builder',
      price: '83,783.88',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'Small',
      size: 'Basic license fee for Atrius Solution builder',
      price: '558,642.02',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'Small',
      size: 'Annual maintenance fee type M',
      price: '83,783.88',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'X-Large',
      size: 'Basic license fee for Atrius Solution builder',
      price: '2,234,568.09',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Gateways',
      model: 'X-Large',
      size: 'Annual maintenance fee type XL',
      price: '335,190.73',
    ),


    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Other Accessories',
      model: 'SP1',
      size: 'Sensor Adaptor Plates Box of 10 for SENW20 Series',
      price: '6,791.57',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Other Accessories',
      model: 'SP2',
      size: 'Sensor Adaptor Plates Box of 10 for innTOUCH/SENW50/HTW Series',
      price: '6,791.57',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Other Accessories',
      model: 'TLBM7',
      size: 'PASStec TouchLBM 7.0" Widescreen, 800x480 pixel (16:9), 350 cd/m2 Ethernet, Power 24V AC/DC, RS485, 197(w)x137(h)x63(d)',
      price: '357,723.52',
    ),
    ProductInfo(
      subcategory: 'Vector Accesories',
      name: 'Other Accessories',
      model: 'USB Flashtool',
      size: 'Flashtool for Innotech Product Firmware Upgrades',
      price: '49,674.24',
    ),




    ProductInfo(
      subcategory: 'Air Release Valve',
      name: 'AVMX series Air Release Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Air Release Valve',
      name: 'AVMX series Air Release Valve',
      model: '2x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Brass Air Release Valve',
      name: 'AVRX Series Air Release Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),


    ProductInfo(
      subcategory: 'Pressure Reducing Valve',
      name: 'PRYS Series SS Pressure Reducing Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),

    ProductInfo(
      subcategory: 'Pressure Reducing Valve',
      name: 'A200 ACV Series Pressure Reducing Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),

    ProductInfo(
      subcategory: 'Floating Valve',
      name: 'A100 ACV Series Floating Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),

    ProductInfo(
      subcategory: 'Check Valve',
      name: 'A300 Series Slow-closure Type Check Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),

    ProductInfo(
      subcategory: 'Pressure Relief Valve',
      name: 'A500 Series Pressure Relief Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),

    ProductInfo(
      subcategory: 'Backflow Preventer',
      name: 'BCVBP Series Backflow Preventers',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),

    ProductInfo(
      subcategory: 'Valves',
      name: 'Alpha Threaded',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),

    ProductInfo(
      subcategory: 'Valves',
      name: 'Alpha Wafer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),

    ProductInfo(
      subcategory: 'Cartridges',
      name: 'Alpha Cartridges',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),

    ProductInfo(
      subcategory: 'Cartridges',
      name: 'Alpha Cool Cartridges',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),

    ProductInfo(
      subcategory: 'Pressure Independent Control Valve',
      name: 'Pressure Independent Control Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),

    ProductInfo(
      subcategory: 'Pressure Independent Control Valve 50-300',
      name: 'Pressure Independent Control Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),

    ProductInfo(
      subcategory: 'Brass Ball Valve',
      name: 'BABV Series Brass Ball Valves',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Brass Ball Valve',
      name: 'BLBV Series Lead Free Brass Ball Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Bronze Ball Valve',
      name: 'BRBV Series Bronze Ball Valves',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Long Neck Ball Valve',
      name: 'BABH Series Long Neck Ball Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Swing Check Valve',
      name: 'BACV Series Brass Swing Check Valves',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Swing Check Valve',
      name: 'BRCV Series Bronze Swing Check Valves',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Swing Check Valve',
      name: 'CVSF Series Flex Swing Check Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Spring Load Check Valve',
      name: 'BRVB Series Spring Load Check Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Dual Plates Check Valve',
      name: 'CVDD Series Dual Plates Check Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Wafer Butterfly Valve',
      name: 'BWLX Series Wafer Butterfly Valve Wafer Concentric Disc',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Wafer Butterfly Valve',
      name: 'BWGX Series Wafer Butterfly Valve Wafer Concentric Disc',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Wafer Butterfly Valve',
      name: 'BWGE Series Wafer Butterfly Valve (Epoxy Coated Disc)',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Electric Actuator Butterfly Valve',
      name: 'BWTX ON/OFF BWAX Modulating Electric Actuator Butterfly Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Electric Actuator Butterfly Valve',
      name: 'BWTE ON/OFF BWAE Modulating Electric Actuator Butterfly Valve (Epoxy Coated Disc)',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Electric Actuator Butterfly Valve',
      name: 'BZTX ON/OFF BZAX Modulating Electric Actuator Butterfly Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Lug Butterfly Valve',
      name: 'BLLX Series Lug Butterfly Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Lug Butterfly Valve',
      name: 'BLGX Series Lug Butterfly Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Flanged Concentric Disc',
      name: 'BZLX Series Butterfly Valve Flanged Concentric Disc',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Flanged Concentric Type',
      name: 'BZGX Series Butterfly Valve Flanged Concentric Type',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Flanged Concentric Type',
      name: 'BZGE Series Butterfly Valve Flanged Concentric Type (Epoxy Coated Disc)',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Fire Protection Signal Feedback Butterfly Valve',
      name: 'BWSX Series Fire Protection Signal Feedback Butterfly Valve with Supervisor Switch',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Omni BEMS Controllers',
      name: 'Innotech OMNI',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Omni BEMS Controllers',
      name: 'Omni Compact',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Omni BEMS Controllers',
      name: 'Omni U10',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Universal Programmable Controller',
      name: 'Universal Programmable Controller',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Intelligent Controller',
      name: 'Intelligent Fan Coil Controller',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Intelligent Controller',
      name: 'Fan Coil Controller with Modbus RTU',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Intelligent Controller',
      name: 'Wall-mounted Controller and Sensor',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Butterfly Valve',
      name: 'BFGX Series Butterfly Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Motorized Butterfly Valve',
      name: 'BFTX Series Motorized Butterfly Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Pneumatic Butterfly Valve',
      name: 'BFPX Series Pneumatic Butterfly Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Damper Actuator',
      name: 'Torque 2 Nm - ECCA Series Standard Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Damper Actuator',
      name: 'Torque 5 Nm - ECCA Series Standard Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Damper Actuator',
      name: 'Torque 10 Nm - ECCA Series Standard Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Damper Actuator',
      name: 'Torque 20 Nm - ECCA Series Standard Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Damper Actuator',
      name: 'Torque 40 Nm - ECCA Series Standard Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Damper Actuator',
      name: 'Torque 2 Nm - ECCM Series Standard Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Damper Actuator',
      name: 'Torque 5 Nm - ECCM Series Standard Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Damper Actuator',
      name: 'Torque 10 Nm - ECCM Series Standard Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Damper Actuator',
      name: 'Torque 40 Nm - ECCM Series Standard Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Damper Actuator',
      name: 'Torque 20 Nm - ECCM Series Standard Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Damper Actuator',
      name: 'Torque 10 Nm - ECSA Series Fast Running Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Damper Actuator',
      name: 'Torque 20 Nm - ECSA Series Fast Running Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Spring Return Damper Actuator',
      name: 'Torque 5 Nm - ECFA Series Spring Return Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Spring Return Damper Actuator',
      name: 'Torque 3 Nm - ECFA Series Spring Return Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Spring Return Damper Actuator',
      name: 'Torque 8 Nm - ECFA Series Spring Return Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Spring Return Damper Actuator',
      name: 'Torque 20 Nm - ECFA Series Spring Return Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Electronic Damper Actuator',
      name: 'Torque 5 Nm - EECM Series Electronic Return Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Electronic Damper Actuator',
      name: 'Torque 10 Nm - EECM Series Electronic Return Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Electronic Damper Actuator',
      name: 'Torque 20 Nm - EECM Series Electronic Return Damper Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Ball Valve Actuator',
      name: 'Torque 5Nm - ECBA Series Ball Valve Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Ball Valve Actuator',
      name: 'Torque 10Nm - ECBA Series Ball Valve Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Ball Valve Actuator',
      name: 'Torque 5Nm - ECBM Series Ball Valve Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Ball Valve Actuator',
      name: 'Torque 10Nm - ECBM Series Ball Valve Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Characteized Disc Ball Valve',
      name: 'EVCB 7000 SERIES CHARACTERIZED DISC BALL VALVE',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Characteized Disc Ball Valve',
      name: 'EVCB 9000 SERIES CHARACTERIZED DISC BALL VALVE',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Motorized Fan Coil Valve',
      name: 'ECMB SERIES MOTORIZED FAN COIL VALVE',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Butterfly Valve',
      name: 'EVBF Series Butterfly Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Butterfly Valve',
      name: 'ECY Series Butterfly Valve Actuator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Rubber Flexible Joint',
      name: 'S10 Series Rubber Flexible Joint PN16 Flanged Single Ball Type',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Rubber Flexible Joint',
      name: 'S30 Series Rubber Expansion Joint PN10 Thread Double Ball Type',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'SS Expansion Joint',
      name: 'L-120 Series SS Expansion Joint',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Brass Gate Valve',
      name: 'BAGV Series Brass Gate Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Brass Gate Valve',
      name: 'BLGV Series Lead Free Brass Gate Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Bronze Gate Valve',
      name: 'BRGV Series Bronze Gate Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Lockable Gate Valve',
      name: 'BAGB Series Brass Lockable Gate Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Lockable Gate Valve',
      name: 'BLGB Series Brass Lockable Lead Free Gate Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Lockable Gate Valve',
      name: 'RVLX Series Lockable NRS Gate Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Extension Length Gate Valve',
      name: 'BAGS Series Extension Length Gate Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'PN16 Flanged Resilient Seated Gate Valve',
      name: 'RVHX Series NRS Gate Valve PN16 Flanged Resilient Seated BS5163 Type',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'PN16 Flanged Resilient Seated Gate Valve',
      name: 'RVHX F4 Series NRS Gate Valve PN16 Flanged Resilent Seated DIN3202 F4 type',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'PN16 Flanged Resilient Seated Gate Valve',
      name: 'RVRX OS&Y Gate Valve PN16 Flanged Resilient Seated EN1171 Type',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Stem Cap Gate Valve',
      name: 'RVCX Series Stem Cap Gate Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Spigot Gate Valve',
      name: 'RVGZ Series Spigot Gate Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Fire Protection Signal Feedback Gate Valve',
      name: 'RVSX Series Fire Protection Signal Feedback Gate Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Brass Globe Valve',
      name: 'BAGL Series Brass Globe Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Bronze Globe Valve',
      name: 'BRGL Series Bronze Globe Valves',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Plunger Valve',
      name: 'FCEX Plunger Valve',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Softwares and Utilities',
      name: 'Genesis II Software',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Softwares and Utilities',
      name: 'Magellan Software',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Y Strainers',
      name: 'BAYS Series Brass Y-Strainers',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Y Strainers',
      name: 'BRYS Series Bronze Y Strainers',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Y Strainers',
      name: 'YSTF Series Y Strainer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Suction Diffuser',
      name: 'YSAX Suction Diffuser',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Basket Strainers',
      name: 'YSTA Series Basket Strainers',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Thermo-Anemometer',
      name: '100MM Vane Thermo-Anemometer Test Instrument',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Thermo-Anemometer',
      name: 'Thermo-Anemometer Probe',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Thermo-Anemometer',
      name: '100mm Vane Thermo-Anemometer Probe',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Thermo-Anemometer',
      name: 'Thermo-Anemometer Test Instrument',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Air Meter',
      name: 'Air Velocity Meter',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Air Meter',
      name: 'Air Meter / Draft Gage',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Air Meter',
      name: 'Averaging Air Flow Grid',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Air Meter',
      name: 'Handheld Indoor Air Quality Meter',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Air Meter',
      name: 'Molded Plastic Air Velocity Meter',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Test Kits',
      name: 'Air Velocity Kits',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Test Kits',
      name: 'Portable Ultrasonic Flowmeter Kit',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Test Kits',
      name: 'Hydronic Differential Pressure Meter Kit',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Test Kits',
      name: 'Test, Adjust, and Balance Kit',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Test Kits',
      name: 'Gas Pressure Test Kit',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Thermo-Hygrometer',
      name: 'Thermo-Hygrometer Probe',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Thermo-Hygrometer',
      name: 'Thermo-Hygrometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Signal Generators',
      name: 'Current / Voltage Signal Generator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Signal Generator',
      name: 'Analog Signal Generator',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Data Logger',
      name: 'Button Data Logger',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Data Logger',
      name: 'High Temperature Data Logger',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Data Logger',
      name: 'LCD Pressure Data Logger',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Data Logger',
      name: 'Pressure/Temperature Data Logger',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Data Logger',
      name: 'Wireless Wi-Fi Data Logger',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Data Logger',
      name: 'Compact USB Data Logger',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Pump',
      name: 'Calibration Pump',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Pump',
      name: 'Hand Pump',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Pump',
      name: 'Pneumatic Calibration Hand Pump',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Pump',
      name: 'Hydraulic Calibration Hand Pump',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Pump',
      name: 'Low Pressure Calibration Pump',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Pump',
      name: 'Pneumatic Hand Pump',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Aspirator Bulb',
      name: 'Aspirator Bulb',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Anemometer',
      name: 'Differential Pressure Anemometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Anemometer',
      name: 'Vaneometer Swing Vane Anemometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Manometer',
      name: 'Single Pressure and Differential Pressure Digital Manometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Manometer',
      name: 'Flex Tube U-tube Manometers',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Manometer',
      name: 'Gas Pressure Manometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Manometer',
      name: 'Precision Digital Pressure Manometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Manometer',
      name: 'Precision Handheld Digital Manometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Manometer',
      name: 'Intrinsically Safe Handheld Digital Manometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Manometer',
      name: 'Handheld Digital Manometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Manometer',
      name: 'Wireless Hydronic Differential Pressure Manometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Manometer',
      name: 'Hydronic Differential Pressure Manometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Manometer',
      name: 'Slack Tube Manometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Manometer',
      name: 'Dual Range Flex-Tube U-Inclined Manometers',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Manometer',
      name: 'Handheld Digital Manometer 477B',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Pressure Module',
      name: 'Wireless Differential Pressure Module',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Thermometer',
      name: 'Dual Input Thermocouple Thermometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Pitot Tube',
      name: 'Ellipsoidal Tip Pitot Tube',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Pitot Tube',
      name: '“S” Type Stainless Steel Pitot Tubes',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Pitot Tube',
      name: 'Straight Stainless Steel Pitot Tube',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Pitot Tube',
      name: 'Telescoping Stainless Steel Pitot Tube',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Pitot Tube',
      name: 'Stainless Steel Pitot Tube',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Tachometer',
      name: 'Portable Digital Tachometer',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Balancing Instrument',
      name: 'SMART Air Hood Balancing Instrument',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Wind Meter',
      name: 'Portable Series Wind Meter',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Wind Meter',
      name: 'Pocket Wind Meter',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Wind Meter',
      name: 'Wind Speed Indicato',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'F510 Variable Frequency Drive',
      name: 'F510 Fan & Pump Drive',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Water Meter',
      name: 'RMT Series RS-485 / Modbus RTU',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Water Meter',
      name: 'Hybrid Digital Multi-Jet Water Meter',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),
    ProductInfo(
      subcategory: 'Water Meter',
      name: 'Hybrid Digital Woltmann Water Meter',
      model: '1x',
      size: 'Descriptions',
      price: '00.00',
    ),















  ];
}